### ISSUE TITLE
root item parameter

### ISSUE THREAD

**Issue by kisst** [kisst/mindmap#8]
if only a sub section of the map is interesting, with url parameter the relevant data section should be possible to be trimmed.
Like so:
```
$ yq r data-to-be.yaml 
this project:
  yaml: null
  rich text:
    color:
      mm-font-color: ff0000
    icon:
      mm-icon: fa-heart
    background:
      mm-background: 0000ff
    allinment: null
  d3j: null
  tooling:
    GitHub:
      mm-hyperlink: https://github.com/kisst/mindmap
  MVP:
    It works: null
  Design principals:
    Data + View should be split: null
    Source data should be human editable: null
    Option to share view: null
    data should version controlled: null
  Implementation:
    In progress: null
```
vs.
```
yq r data-to-be.yaml "this project.tooling"
GitHub:
  mm-hyperlink: https://github.com/kisst/mindmap
```

**Comment by evenicoulddoit** [comment]
Questions:

* You'd want this to actually in essence *remove* the other data altogether? So, if you provided a `?root` parameter e.g. of `this-project.tooling` then you _couldn't_ see any of the other nodes?
* How would this work with `?initial` - or does it replace the `?initial` altogether?
  * If it _didn't_, and I wanted - in your example - to set the `root` as `this-project.tooling.github` would I need to provide it like that? Or would I just give the initial as `github`?

**Comment by kisst** [comment]
My idea was that setting the route, does remove the parent data, and load in only the partial map, so the initial would be relative to that.
So given `this-project.design-principals` as a `root` and `option-to-share-view.foo` as initial would give a map of the `Design principals` with everything but the `Option to share view` `Foo` closed.

Reasoning behind the thinking is that you might want to share a smaller section of the map without any of the noise around it. Maybe if root is set, a navigation bar can show as an indication that you are watching only part of the map, like in webshops, just the categories, so if you choose to you can zoom back out ( without just click and no url edit  )

**Comment by evenicoulddoit** [comment]
Got it
